<a href="https://colab.research.google.com/github/Manojna007/machineLearning/blob/main/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X

array([[2., 9.],
       [1., 5.],
       [3., 6.]])

In [ ]:
y

array([[92.],
       [86.],
       [89.]])

In [ ]:
X = X/np.amax(X,axis=0)
X

array([[0.66666667, 1.        ],
       [0.33333333, 0.55555556],
       [1.        , 0.66666667]])

In [ ]:
y = y/100
y

array([[0.92],
       [0.86],
       [0.89]])

In [ ]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [ ]:
def derivatives_sigmoid(x):
    return x * (1 - x)

In [ ]:
epoch=5000                                                      	#Setting training iterations 
lr=0.1                                                          	#Setting learning rate
inputlayer_neurons = 2                                          	#number of features in data set 
hiddenlayer_neurons = 3                                         	#number of hidden layers neurons 
output_neurons = 1                                              	#number of neurons at output layer

In [ ]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons)) 
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [ ]:
for i in range(epoch):
    hinp1=np.dot(X,wh)
    hinp=hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1=np.dot(hlayer_act,wout)
    outinp= outinp1+ bout
    output = sigmoid(outinp)
    
    EO = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = EO* outgrad
    EH = d_output.dot(wout.T)
    
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad

In [ ]:
wout += hlayer_act.T.dot(d_output) *lr
wh += X.T.dot(d_hiddenlayer) *lr

print("Input: \n" + str(X)) 
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.86204318]
 [0.84954912]
 [0.86162489]]
