<a href="https://colab.research.google.com/github/Manojna007/machineLearning/blob/main/Knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
from sklearn.model_selection import train_test_split



In [2]:

iris_dataset=load_iris()
print("\n TARGET NAMES: \n ", iris_dataset.target_names)
X_train, X_test, y_train, y_test = train_test_split(iris_dataset["data"], iris_dataset["target"], random_state=0)


 TARGET NAMES: 
  ['setosa' 'versicolor' 'virginica']


In [3]:
print("\n X TRAIN \n", X_train)
print("\n X TEST \n", X_test)
print("\n Y TRAIN \n", y_train)
print("\n Y TEST \n", y_test)


 X TRAIN 
 [[5.9 3.  4.2 1.5]
 [5.8 2.6 4.  1.2]
 [6.8 3.  5.5 2.1]
 [4.7 3.2 1.3 0.2]
 [6.9 3.1 5.1 2.3]
 [5.  3.5 1.6 0.6]
 [5.4 3.7 1.5 0.2]
 [5.  2.  3.5 1. ]
 [6.5 3.  5.5 1.8]
 [6.7 3.3 5.7 2.5]
 [6.  2.2 5.  1.5]
 [6.7 2.5 5.8 1.8]
 [5.6 2.5 3.9 1.1]
 [7.7 3.  6.1 2.3]
 [6.3 3.3 4.7 1.6]
 [5.5 2.4 3.8 1.1]
 [6.3 2.7 4.9 1.8]
 [6.3 2.8 5.1 1.5]
 [4.9 2.5 4.5 1.7]
 [6.3 2.5 5.  1.9]
 [7.  3.2 4.7 1.4]
 [6.5 3.  5.2 2. ]
 [6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]
 [6.9 3.2 5.7 2.3]
 [6.5 3.  5.8 2.2]
 [6.4 2.8 5.6 2.1]
 [5.1 3.8 1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [6.5 3.2 5.1 2. ]


In [4]:
kn = KNeighborsClassifier(n_neighbors=5)
kn.fit(X_train, y_train)

KNeighborsClassifier()

In [5]:
x_new = np.array([[5, 2.9, 1, 0.2]])
print("\n XNEW \n",x_new)
prediction = kn.predict(x_new)
print("\n Predicted target value: {}\n".format(prediction))
print("\n Predicted feature name: {}\n".format(iris_dataset["target_names"][prediction]))


 XNEW 
 [[5.  2.9 1.  0.2]]

 Predicted target value: [0]


 Predicted feature name: ['setosa']



In [6]:
for i in range(len(X_test)):
  x = X_test[i]
  x_new = np.array([x])
  prediction = kn.predict(x_new)
  print("*",x_new)
  print("Actual : {0} {1}, Predicted :{2}{3}\n".format(y_test[i],iris_dataset["target_names"][y_test[i]],prediction,iris_dataset["target_names"][ prediction]))
print("\n TEST SCORE[ACCURACY]: {:.2f}\n".format(kn.score(X_test, y_test)))

* [[5.8 2.8 5.1 2.4]]
Actual : 2 virginica, Predicted :[2]['virginica']

* [[6.  2.2 4.  1. ]]
Actual : 1 versicolor, Predicted :[1]['versicolor']

* [[5.5 4.2 1.4 0.2]]
Actual : 0 setosa, Predicted :[0]['setosa']

* [[7.3 2.9 6.3 1.8]]
Actual : 2 virginica, Predicted :[2]['virginica']

* [[5.  3.4 1.5 0.2]]
Actual : 0 setosa, Predicted :[0]['setosa']

* [[6.3 3.3 6.  2.5]]
Actual : 2 virginica, Predicted :[2]['virginica']

* [[5.  3.5 1.3 0.3]]
Actual : 0 setosa, Predicted :[0]['setosa']

* [[6.7 3.1 4.7 1.5]]
Actual : 1 versicolor, Predicted :[1]['versicolor']

* [[6.8 2.8 4.8 1.4]]
Actual : 1 versicolor, Predicted :[1]['versicolor']

* [[6.1 2.8 4.  1.3]]
Actual : 1 versicolor, Predicted :[1]['versicolor']

* [[6.1 2.6 5.6 1.4]]
Actual : 2 virginica, Predicted :[2]['virginica']

* [[6.4 3.2 4.5 1.5]]
Actual : 1 versicolor, Predicted :[1]['versicolor']

* [[6.1 2.8 4.7 1.2]]
Actual : 1 versicolor, Predicted :[1]['versicolor']

* [[6.5 2.8 4.6 1.5]]
Actual : 1 versicolor, Predicted :[